erDiagram
    silver_ratings {
        INT rating_id
        INT customer_id
        INT branch_id
        INT employee_id
        INT treatment_id
        FLOAT rating_value
        STRING comment
        DATE rating_date
        TIMESTAMP timestamp
        TIMESTAMP ingestion_time
        FLOAT data_quality_score
    } 