version: "3.9"

services:
  spark-bronze-ratings:
    image: bitnami/spark:3.5.1
    container_name: spark-bronze-ratings
    volumes:
      - ./bronze:/app/bronze
      - ./silver:/app/silver
      - ./gold:/app/gold
    working_dir: /app
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.3
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=admin
      --conf spark.hadoop.fs.s3a.secret.key=password
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      bronze/bronze_ratings.py
    networks:
      - data-network
    depends_on:
      - minio-init

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    networks:
      - data-network

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        mc alias set local http://minio:9000 admin password &&
        mc mb local/warehouse || true &&
        mc mb local/raw-data || true &&
        mc cp /uploads/ratings.csv local/raw-data/ &&
        echo '✅ MinIO initialized with warehouse and raw-data buckets.'
      "
    volumes:
      - ./ratings.csv:/uploads/ratings.csv
    networks:
      - data-network

networks:
  data-network:
    driver: bridge

volumes:
  minio-data:
