erDiagram
    dim_branches {
        INT branch_id
        STRING name
        STRING city
        STRING address
        BOOLEAN active
        DATE opening_date
        TIMESTAMP created_timestamp
    } 