erDiagram
    dim_customers {
        INT customer_id
        INT version_id
        STRING first_name
        STRING last_name
        STRING email
        STRING phone
        STRING address
        STRING city
        DATE start_date
        DATE end_date
        BOOLEAN is_current
        TIMESTAMP created_timestamp
    } 