erDiagram
    dim_employees {
        INT employee_id
        STRING first_name
        STRING last_name
        STRING role
        INT experience_years
        BOOLEAN active
        DATE hire_date
        INT branch_id
        TIMESTAMP created_timestamp
    } 