erDiagram
    bronze_ratings {
        INT customer_id
        INT branch_id
        INT employee_id
        INT treatment_id
        FLOAT rating_value
        STRING comment
        TIMESTAMP timestamp
        TIMESTAMP processed_timestamp
        STRING _kafka_topic
        INT _kafka_partition
        BIGINT _kafka_offset
    } 