services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - iceberg_net

  redis:
    image: redis:6
    container_name: airflow-redis
    networks:
      - iceberg_net

  webserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    restart: always
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: mydevsecretkey
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW_CONN_SPARK_DEFAULT: "spark://spark-iceberg:7077"
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: myteamemailshenkar@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR_APP_PASSWORD>
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: myteamemailshenkar@gmail.com
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    entrypoint: airflow webserver
    networks:
      - iceberg_net

  scheduler:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow-scheduler
    depends_on:
      - webserver
    restart: always
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: mydevsecretkey
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_SPARK_DEFAULT: "spark://spark-iceberg:7077"
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: myteamemailshenkar@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR_APP_PASSWORD>
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: myteamemailshenkar@gmail.com
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: airflow scheduler
    networks:
      - iceberg_net

  worker:
    hostname: airflow-worker
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow-worker
    depends_on:
      - scheduler
    restart: always
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: mydevsecretkey
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_SPARK_DEFAULT: "spark://spark-iceberg:7077"
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: myteamemailshenkar@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR_APP_PASSWORD>
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: myteamemailshenkar@gmail.com
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: airflow celery worker
    networks:
      - iceberg_net

  airflow-init:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow-init
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: myteamemailshenkar@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR_APP_PASSWORD>
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: myteamemailshenkar@gmail.com
    entrypoint: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
    networks:
      - iceberg_net

networks:
  iceberg_net:
    external: true
