version: "3"

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - iceberg_net

  redis:
    image: redis:6
    container_name: airflow-redis
    networks:
      - iceberg_net

  webserver:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    ports:
      - 8081:8080
    entrypoint: >
      bash -c "pip install -r /requirements.txt && airflow webserver"
    networks:
      - iceberg_net

  scheduler:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow-scheduler
    depends_on:
      - webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    entrypoint: >
      bash -c "pip install -r /requirements.txt && airflow scheduler"
    networks:
      - iceberg_net

  worker:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow-worker
    depends_on:
      - scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    entrypoint: >
      bash -c "pip install -r /requirements.txt && airflow celery worker"
    networks:
      - iceberg_net

  airflow-init:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow-init
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    volumes:
      - ./requirements.txt:/requirements.txt
    entrypoint: >
      bash -c "pip install -r /requirements.txt &&
      airflow db upgrade &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    networks:
      - iceberg_net

networks:
  iceberg_net:
    external: true
